In [1]:
I=range(10000000)

In [2]:
import numpy as np

In [3]:
d=np.arange(10000000)

In [6]:
%time for i in range(1,10): r=[x*2 for x in I ]

Wall time: 16.4 s


In [7]:
%time for i in range(1,10): r=d*2

Wall time: 612 ms


In [11]:
x=np.zeros((4,4))

In [12]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((7,7))

array([[2.67746501e+161, 2.02797605e+267, 5.57620871e+228,
        5.65899571e+276, 1.33028094e+246, 4.11515076e+127,
        1.44139578e+214],
       [8.78992634e+223, 5.81541226e+180, 1.24386952e+214,
        3.99194940e+252, 1.38489780e+246, 4.83241318e+276,
        5.64054287e-254],
       [1.24846720e+243, 5.30343399e+180, 1.65320860e-292,
        1.50806342e+161, 8.89489993e+252, 2.06917447e+161,
        5.04533058e+223],
       [5.53213548e+127, 7.52503934e+199, 2.11495889e+214,
        1.50489131e+161, 5.29367972e+180, 7.50048887e+247,
        6.49005419e+180],
       [6.49511980e+180, 2.78106904e+180, 1.56049919e+184,
        1.73822437e+286, 4.26019907e-090, 1.19926084e+141,
        5.75458360e-133],
       [1.06767444e-090, 1.30811469e+295, 1.16272749e+007,
        6.97497790e-056, 4.91378824e+247, 2.26467698e-085,
        2.29109253e-085],
       [2.26377519e+136, 9.61266863e+135, 3.00083378e+280,
        1.29924029e+200, 2.20519013e-094, 2.58241664e-176,
        1.29924029

In [16]:
l=[1,3,4,6,7]

In [17]:
np.array(l)

array([1, 3, 4, 6, 7])

In [21]:
x=np.arange(1,100,10)

In [22]:
x.shape

(10,)

In [24]:
p=np.zeros((10,10))

In [25]:
p.shape

(10, 10)

In [26]:
y=p.reshape((2,2,5,5))

In [27]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [31]:
y.ndim

4

In [33]:
y.dtype

dtype('float64')

In [34]:
arry = np.array([[1,2,3,4],[5,6,7,8]])

In [35]:
arry

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arry + arry

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [37]:
arry - arry

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
1 / arry

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [39]:
arry ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [40]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [42]:
y.itemsize

8

In [43]:
y.data